# Generated by Django 5.0.7 on 2024-08-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='people_you_may_know',
        ),
        migrations.RemoveField(
            model_name='user',
            name='personal_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='posts_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='public_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='workplace_city_town',
        ),
        migrations.RemoveField(
            model_name='user',
            name='workplace_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='workplace_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='workplace_position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='workplace_time_period',
        ),
        migrations.DeleteModel(
            name='FriendshipRequest',
        ),
    ]
